#!/bin/bash
clear
read -p "PLEASE ENTER TO CONTINUE " ENTER
echo -e $red PLEASE ENTER 4 DIGITS PORT
read -p "ENTER PORT: " love
if [ $love == "0" ]; then
echo -e $red NGROK STARTING
./ngrok http $love
