#!/bin/bash
clear
./ngrok authtoken 1qbAN2lJJ9MF5mob07DJ8myTeW2_6dBKe98cqBKn8YJprkHCw
read -p "PRESS ENTER TO CONTINUE " ENTER
echo -e $red ENTER 4 DIGITS PORT
read -p "ENTER PORT: " idra
if [ $idra == "0" ]; then
echo -e $red NGROK STARTING........
else
./ngrok tcp $idra
fi
sleep 1
exit
