#!/bin/bash
clear
./ngrok authtoken 1qbAN2lJJ9MF5mob07DJ8myTeW2_6dBKe98cqBKn8YJprkHCw
clear
echo -e $red ███╗░░██╗░██████╗░██████╗░░█████╗░██╗░░██╗
echo -e $red ████╗░██║██╔════╝░██╔══██╗██╔══██╗██║░██╔╝
echo -e $red ██╔██╗██║██║░░██╗░██████╔╝██║░░██║█████═╝░
echo -e $red ██║╚████║██║░░╚██╗██╔══██╗██║░░██║██╔═██╗░
echo -e $red ██║░╚███║╚██████╔╝██║░░██║╚█████╔╝██║░╚██╗
echo -e $red ╚═╝░░╚══╝░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝ v11.0
read -p "🇵​​​​​🇷​​​​​🇪​​​​​🇸​​​​​🇸​​​​​ 🇪​​​​​🇳​​​​​🇹​​​​​🇪​​​​​🇷​​​​​ 🇹​​​​​🇴​​​​​ 🇨​​​​​🇴​​​​​🇳​​​​​🇹​​​​​🇮​​​​​🇳​​​​​🇺​​​​​🇪​​​​​ " ENTER
echo -e $red ENTER 4 NUMBER PORTS
read -p "ENTER PORT: " idra
if [ $idra == "0" ]; then
else
./ngrok tcp $idra
fi
sleep 1
exit
